logging:
  level:
    #        tk.mybatis: DEBUG
    com.github.wxiaoqi.security.common: DEBUG
spring:
  application:
    name: UDAX-WALLET
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  datasource:
    name: test
    url: jdbc:mysql://${MYSQL_HOST:192.168.1.198}:${MYSQL_PORT:3306}/wallet?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=PRC&useSSL=false
    username: root
    password: ENC(I98pRGIfN/ysHu/7FEoEPaTjbV9XQ9dY)

    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  sleuth:
    enabled: true
    http:
      legacy:
        enabled: true
  redis:
    pool:
    max-active: 300
    max-idle: 100
    max-wait: 1000
    host: ${REDIS_HOST:192.168.1.198}
    port:  ${REDIS_PORT:6379}
    password: udaxredis8888
    # 服务或应用名
    sysName: UDAX-WALLET
    enable: true
sample:
  zipkin:
    enabled: false

mybatis:
  basepackage: com.github.wxiaoqi.security.common
  xmlLocation: classpath:mapper/**/*.xml
  mapper-locations: "classpath*:mapper/**/*.xml"

server:
  port: 8762


feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true


hystrix:
  threadpool:
    default:
      coreSize: 1000 ##并发执行的最大线程数，默认10
      maxQueueSize: 1000 ##BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 110000


# 配置swagger
swagger:
  enabled: true
  base-package: com.github.wxiaoqi.security.admin
  title: UDAX-WALLET
  version: 1.0.0.SNAPSHOT
  description: 管理后端服务
  contact:
    name: admin

auth:
  serviceId: ace-auth
  user:
    token-header: Authorization
  client:
    id: UDAX-WALLET
    secret: 123456
    token-header: x-client-token



management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false
jwt:
  token-header: Authorization
  expire: 14400
  rsa-secret: xx1WET12^%3^(WE45

client:
  walletKey: 11223344
  merchantKey: 11223344
  #区块链与钱包加密KEY
  tokenKey: 1234567890
  signKey: 12345678
sftp:
  host: 192.168.1.198
  port: 22
  timeout: 5000
  aliveMax: 10
  nginx:
    path: http://${sftp.host}/upload/
  user:
    name: sftp
    password: udaxsftp8888
udax:
  quotation: http://52.221.232.245:8080/wallet/quotation
  lastprices: http://52.221.232.245:8080/wallet/getLastPrices
ifTestEnv:
  value: true
#区块链连接url(测试环境)
blockchain:
  pushaddress: http://52.221.232.245:8080/coinWallet/
  ip: 52.221.232.245
# 不需要进行验证权限的请求 逗号分隔
requestUrl:
    config: /basicSymbol/userQuote,/basicSymbol/all,/whiteExchInfo/all,/group/tree,/dept/all,/groupType/selectGroupTypeByUser,/user/front/menu/all,/menu/tree,/basicSymbol/AllList,/basicSymbol/quoteAll,/element/list,/basicSymbol/page,/chargeTemplate/all,/purchaseLevel/all

jasypt:
  encryptor:
    password: test